server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路徑
  type-aliases-package: com.bryant.springcloud.entity # 所有Entity別名類所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  application:
    name: microservicecloud-dept //對外暴露的微服務的名字

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 當前數據源操作類型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驅動包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC # 資料庫名稱
    username: root
    password: sa123456
    dbcp2:
      min-idle: 5 # 資料庫連接池的最小維持連接數
      initial-size: 5 # 初始化連接數
      max-total: 5 # 最大連接數
      max-wait-millis: 200 # 等待連接獲取的最大超時時間
